export const initConfigurationPayStructure = {
  PayStructureSettings: {
    PayStructureType: 'Commission',
    PotentialBonus: 50,
    CommissionPayout: 30,
    MaxCommissionPayout: 60,
    SalaryGuaranteePayout: 0,
    MaxSalaryGuaranteePayout: 0,
    HourlyPayout: 0.0,
    MaxHourlyPayout: 0.0,
    AllowSalaryAndCommissionCombination: false,
    RequiresWorkingTimeOver: false,
    WorkingTimeType: 'Day',
    DayMinHour: 0,
    WeekType: 'MinDayAndHour',
    WeekMinHour: 0,
    WeekMinDay: 0,
    WeekMinTotalHour: 0,
    MonthType: 'MinDayAndHour',
    MonthMinHour: 0,
    MonthMinDay: 0,
    MonthMinTotalHour: 0,
    BaseOnPeriodType: 'MinDayAndHour',
    BaseOnPeriodMinHour: 0,
    BaseOnPeriodMinDay: 0,
    BaseOnPeriodMinTotalHour: 0,
  },
  TipOnCC: {
    TipOnCCType: 'TipOnCCFeeFromCreditCard',
    TipOnCCFeeFromCreditCard: '0',
    TipOnCCDailyFixedFee: '0',
  },
  DailySurcharge: {
    DailySurchargeType: 'DailySurchargeFromCommission',
    DailySurchargeFromCommission: 0,
    DailySurchargeFixedSurcharge: 0,
    DailySurchargeWorkingTimeType: 'Day',
    DailySurchargeWorkingDailyMinHour: 8,
    DailySurchargeWorkingWeeklyType: 'MinDayAndHour',
    DailySurchargeWorkingWeeklyMinHour: 0,
    DailySurchargeWorkingWeeklyMinDay: 0,
    DailySurchargeWorkingWeeklyMinTotalHour: 0,
  },
  ProductCharge: {
    ProductChargeType: 'Based on Service',
    BaseOnTicketAmount: 0,
    BaseOnTicketMinChargeAmount: 0,
    BaseOnTicketMinChargePercent: 0,
  },
  ProductCommission: {
    AllowProductCommission: true,
    ProductCommissionPercent: 0,
    MaxPayoutProductCommissionPercent: 0,
  },
  HoldCash: { AllowHoldCash: true },
  CheckCashPercentage: {
    TipFeeCheckPercentage: 0,
    SurchargeCheckPercentage: 0,
  },
};
export const initAddPayStructure = {
  PayStructure: {
    Name: '',
  },
  Configuration: initConfigurationPayStructure,
};
